# Generated by Django 3.2.8 on 2021-11-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activate_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Activation key'),
        ),
        migrations.AddField(
            model_name='user',
            name='activate_key_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
